version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sweetadmin
    ports:
      - "3306:3306"

  backend:
    build: ./sweetadmin-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: sweetadmin
      JWT_SECRET: sweetadmin_secret_2025
      RECAPTCHA_SECRET: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    depends_on:
      - db

  frontend:
    build: ./sweetadmin-frontend
    ports:
      - "80:80"
    depends_on:
      - backend